### ISSUE TITLE
Add ssl cert

### ISSUE THREAD

**Issue by davidruffner** [Code4Newark/codefornewark.org#30]
Make sure to update links in site to https

**Comment by Sun-Wukong** [comment]
After taking a look at the [Guide to Securing your Github Pages Site with HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/), I learned that there is no HTTPS support for Github Pages, under a custom domain. Below is a screenshot of a relevant subsection in the doc

![not_https_for_custom_domains](https://user-images.githubusercontent.com/5842787/38110545-04e79a56-336a-11e8-8b63-55aa8ce14b6f.PNG)

**Comment by davidruffner** [comment]
@Sun-Wukong Thanks Jason for looking into this. Yeah unfortunately they do not support fully secure websites. But it looks like you can use Cloudflare to provide some security benefits.

This [post]( https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc) described it pretty well:
> It’s important to note that this setup is not fully secure — the connection between CloudFlare and GitHub pages is not secured. Since GitHub doesn’t have a SSL certificate for your domain, Full SSL is not possible with a custom domain. However, this setup does provide some protection your users (e.g. from the hacker on the same unsecured Wi-Fi network), and it allows your site to behave as if it has SSL (e.g. for web crawlers, APIs).

I followed that post and a [guide](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) from Cloudflare to setup at least partial ssl for the website. It's propagating now...

**Comment by Sun-Wukong** [comment]
Ah, that's still pretty helpful @davidruffner. The SSL setup via Cloudflare would definitely help out with SEO. I was able to get a PDF report of an HTTPS test, and it was a success! I'll update this with [a link to the test results](https://www.ssllabs.com/ssltest/analyze.html?d=codefornewark.org&latest)

**Comment by Sun-Wukong** [comment]
Permission to close #30, @davidruffner ?

**Comment by davidruffner** [comment]
Yup, go ahead! Thanks Jason!
