### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by davidruffner** [Code4Newark/codefornewark.org#33]
clicking anything off the drop down on mobile leads to
![image](https://user-images.githubusercontent.com/6666044/40486918-9cb9fe68-5f30-11e8-8526-1a87dfce4c5d.png)

**Comment by Sun-Wukong** [comment]
Update: after following through the dropdown links( Chrome For Android ), it seems that the links bring me to the proper part of the site? Any specifics regarding browser usage? I'd like to test across most major mobile browsers

**Comment by Sun-Wukong** [comment]
Links seem to work well on my mobile browsers. Permission to close?

**Comment by davidruffner** [comment]
Thanks for checking that! I'll close it now.
