### ISSUE TITLE
The "Contribute to your community with tech!" Send button should have a green background and white font

### ISSUE THREAD

**Issue by chocolatechimpcookie** [Code4Newark/codefornewark.org#35]
The grey here implies inactive even if you fill out the form:

![image](https://user-images.githubusercontent.com/6192164/44179299-37807600-a0c4-11e8-951c-5d48d784418d.png)

It should look kinda like this:

![image](https://user-images.githubusercontent.com/6192164/44179366-74e50380-a0c4-11e8-819e-35a107c6a213.png)

**Comment by chocolatechimpcookie** [comment]
I can do this one.

**Comment by chocolatechimpcookie** [comment]
@davidruffner My latest pushes should fix this. 

**Note**: it seemed to push files to .bundle as well.

**Comment by davidruffner** [comment]
@chocolatechimpcookie It looks good! Thanks for doing that (commits 8a10d7823c681d8a09bce41e88ef8361ffe6a97e, aa9d5719091b123b40da896213588a29d6b535f9, ec36a491147a82243d5ad736f9e09810d41294d2).

I'm not sure what the `BUNDLE_PATH: "vendor/bundle"` does. It would be good to find out, but I think we can close this issue for now.

**Comment by chocolatechimpcookie** [comment]
I think it got added when I tried to compile and run the project.
